# Generated by Django 4.1 on 2022-09-14 07:49

from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import explorers.models
import os
import simple_history.models
import uuid
from django.core import serializers
import lzma


def load_carbon_emission_factors(apps, schema_editor):
    if os.environ.get('CI'):
        return
    # this is to use the model on currenct state without new fields that added in future migrations
    # else it will throw programming error due to the model load do not consist of the new field from the future migration
    original_apps = serializers.python.apps
    serializers.python.apps = apps
    fixture_file = 'explorers/fixtures/2023-09-08-load_carbon_emission_factors.json.xz'

    with lzma.open(fixture_file, 'rt') as file:
        file_content = file.read()

    # Deserialize the file content
    objects = serializers.deserialize(
        'json', file_content, ignorenonexistent=True)

    for obj in objects:
        obj.save()

    serializers.python.apps = original_apps


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSourceEmissionFactor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_source_page_link', models.URLField(
                    blank=True, help_text='URL of the data that we scraped from.', max_length=2048, null=True)),
                ('external_source_id', models.CharField(
                    help_text='ID of the data that we scraped from.', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('source', models.CharField(
                    help_text='Original source of the information, e.g. GHG Protocol, EPA, etc.', max_length=128)),
                ('source_link', models.URLField(
                    help_text='URL of original source.', max_length=2048)),
                ('year_released', models.IntegerField(validators=[
                 django.core.validators.MinValueValidator(1970), explorers.models.max_current_year])),
                ('region', models.CharField(max_length=128)),
                ('region_code', models.CharField(max_length=64)),
                ('sector', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('unit_type', models.CharField(max_length=64)),
                ('lca_activity', models.CharField(max_length=128)),
                ('method_applied', models.CharField(max_length=64)),
                ('method_supported', models.CharField(max_length=64)),
                ('origin', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('emission_factor_value', models.JSONField(decoder=explorers.models.DecimalDecoder,
                                                           default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('external_source_name', models.CharField(max_length=32)),
                ('raw_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateExternalSourceEmissionFactor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('external_source_page_link', models.URLField(
                    blank=True, max_length=2048, null=True)),
                ('external_source_id', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('source_link', models.URLField(
                    blank=True, max_length=2048, null=True)),
                ('year_released', models.IntegerField(blank=True, null=True, validators=[
                 django.core.validators.MinValueValidator(1970), explorers.models.max_current_year])),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('region_code', models.CharField(
                    blank=True, max_length=64, null=True)),
                ('sector', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=64, null=True)),
                ('lca_activity', models.CharField(
                    blank=True, max_length=128, null=True)),
                ('method_applied', models.CharField(
                    blank=True, max_length=64, null=True)),
                ('method_supported', models.CharField(
                    blank=True, max_length=64, null=True)),
                ('origin', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('emission_factor_value', models.JSONField(blank=True, decoder=explorers.models.DecimalDecoder,
                                                           default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('external_source_name', models.CharField(
                    blank=True, max_length=32, null=True)),
                ('remarks', models.CharField(blank=True, max_length=256)),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('external_source_emission_factor', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='explorers.externalsourceemissionfactor')),
            ],
        ),
        migrations.CreateModel(
            name='PantasEmissionFactor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4,
                                                 editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('description', models.TextField(editable=False)),
                ('source', models.CharField(editable=False, max_length=128)),
                ('source_link', models.URLField(editable=False, max_length=2048)),
                ('year_released', models.IntegerField(editable=False, validators=[
                 django.core.validators.MinValueValidator(1970), explorers.models.max_current_year])),
                ('region', models.CharField(editable=False, max_length=128)),
                ('region_code', models.CharField(editable=False, max_length=64)),
                ('sector', models.CharField(editable=False, max_length=64)),
                ('category', models.CharField(editable=False, max_length=64)),
                ('unit_type', models.CharField(editable=False, max_length=64)),
                ('lca_activity', models.CharField(editable=False, max_length=128)),
                ('method_applied', models.CharField(
                    editable=False, max_length=64)),
                ('method_supported', models.CharField(
                    editable=False, max_length=64)),
                ('origin', models.CharField(editable=False, max_length=64)),
                ('unit', models.CharField(editable=False, max_length=64)),
                ('emission_factor_value', models.JSONField(decoder=explorers.models.DecimalDecoder,
                                                           default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('external_source_name', models.CharField(
                    editable=False, max_length=32)),
                ('external_source_emission_factor', models.OneToOneField(editable=False,
                                                                         on_delete=django.db.models.deletion.CASCADE, to='explorers.externalsourceemissionfactor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUpdateExternalSourceEmissionFactor',
            fields=[
                ('id', models.IntegerField(auto_created=True,
                                           blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(
                    blank=True, editable=False, null=True)),
                ('external_source_page_link', models.URLField(
                    blank=True, max_length=2048, null=True)),
                ('external_source_id', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('source_link', models.URLField(
                    blank=True, max_length=2048, null=True)),
                ('year_released', models.IntegerField(blank=True, null=True, validators=[
                 django.core.validators.MinValueValidator(1970), explorers.models.max_current_year])),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('region_code', models.CharField(
                    blank=True, max_length=64, null=True)),
                ('sector', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=64, null=True)),
                ('lca_activity', models.CharField(
                    blank=True, max_length=128, null=True)),
                ('method_applied', models.CharField(
                    blank=True, max_length=64, null=True)),
                ('method_supported', models.CharField(
                    blank=True, max_length=64, null=True)),
                ('origin', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('emission_factor_value', models.JSONField(blank=True, decoder=explorers.models.DecimalDecoder,
                                                           default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('external_source_name', models.CharField(
                    blank=True, max_length=32, null=True)),
                ('remarks', models.CharField(blank=True, max_length=256)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(
                    max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('external_source_emission_factor', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                                      on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='explorers.externalsourceemissionfactor')),
                ('history_user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical update external source emission factor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPantasEmissionFactor',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('external_id', models.UUIDField(
                    db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('description', models.TextField(editable=False)),
                ('source', models.CharField(editable=False, max_length=128)),
                ('source_link', models.URLField(editable=False, max_length=2048)),
                ('year_released', models.IntegerField(editable=False, validators=[
                 django.core.validators.MinValueValidator(1970), explorers.models.max_current_year])),
                ('region', models.CharField(editable=False, max_length=128)),
                ('region_code', models.CharField(editable=False, max_length=64)),
                ('sector', models.CharField(editable=False, max_length=64)),
                ('category', models.CharField(editable=False, max_length=64)),
                ('unit_type', models.CharField(editable=False, max_length=64)),
                ('lca_activity', models.CharField(editable=False, max_length=128)),
                ('method_applied', models.CharField(
                    editable=False, max_length=64)),
                ('method_supported', models.CharField(
                    editable=False, max_length=64)),
                ('origin', models.CharField(editable=False, max_length=64)),
                ('unit', models.CharField(editable=False, max_length=64)),
                ('emission_factor_value', models.JSONField(decoder=explorers.models.DecimalDecoder,
                                                           default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('external_source_name', models.CharField(
                    editable=False, max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(
                    max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('external_source_emission_factor', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True,
                                                                      on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='explorers.externalsourceemissionfactor')),
                ('history_user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pantas emission factor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExternalSourceEmissionFactor',
            fields=[
                ('id', models.IntegerField(auto_created=True,
                                           blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('external_source_page_link', models.URLField(
                    blank=True, help_text='URL of the data that we scraped from.', max_length=2048, null=True)),
                ('external_source_id', models.CharField(
                    help_text='ID of the data that we scraped from.', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('source', models.CharField(
                    help_text='Original source of the information, e.g. GHG Protocol, EPA, etc.', max_length=128)),
                ('source_link', models.URLField(
                    help_text='URL of original source.', max_length=2048)),
                ('year_released', models.IntegerField(validators=[
                 django.core.validators.MinValueValidator(1970), explorers.models.max_current_year])),
                ('region', models.CharField(max_length=128)),
                ('region_code', models.CharField(max_length=64)),
                ('sector', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('unit_type', models.CharField(max_length=64)),
                ('lca_activity', models.CharField(max_length=128)),
                ('method_applied', models.CharField(max_length=64)),
                ('method_supported', models.CharField(max_length=64)),
                ('origin', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('emission_factor_value', models.JSONField(decoder=explorers.models.DecimalDecoder,
                                                           default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('external_source_name', models.CharField(max_length=32)),
                ('raw_data', models.JSONField(default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(
                    max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical external source emission factor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='externalsourceemissionfactor',
            constraint=models.UniqueConstraint(fields=(
                'external_source_id', 'external_source_name'), name='externalsourceemissionfactor_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='updateexternalsourceemissionfactor',
            constraint=models.UniqueConstraint(fields=(
                'external_source_id', 'external_source_name'), name='updateexternalsourceemissionfactor_unique_constraint'),
        ),
        # move from 0005 to here due to loaddata errors
        migrations.AddField(
            model_name='externalsourceemissionfactor',
            name='external_source_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalexternalsourceemissionfactor',
            name='external_source_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='ClimatiqVersion',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('latest', models.CharField(editable=False, max_length=32)),
                ('latest_minor', models.PositiveIntegerField(editable=False)),
                ('latest_major', models.PositiveIntegerField(editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(load_carbon_emission_factors,
                             migrations.RunPython.noop),
    ]
