# Generated by Django 4.1 on 2022-11-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0001_initial'),
    ]

    # migrations are done in 0001_initial now
    operations = []
