# Generated by Django 4.1.9 on 2023-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0004_historicalregionconfiguration_and_more'),
    ]

    # migrations are done in 0001_initial now
    operations = []
