# Generated by Django 4.2.11 on 2024-05-28 03:45

from django.db import migrations, models


def update_emission_factor_activity_id(apps, schema_editor):
    """
    Update activity_id in ExternalSourceEmissionFactor and PantasEmissionFactor models.
    """
    ExternalSourceEmissionFactorModel = apps.get_model(
        'explorers', 'ExternalSourceEmissionFactor')
    PantasEmissionFactorModel = apps.get_model(
        'explorers', 'PantasEmissionFactor')

    # Get all ExternalSourceEmissionFactor objects with non-empty raw_data
    climatiq_api_ef_objects = ExternalSourceEmissionFactorModel.objects.exclude(
        raw_data='{}')

    # Create a list of PantasEmissionFactor objects corresponding to the climatiq_api_ef_objects
    pantas_ef_objects = []
    for climatiq_api_ef_object in climatiq_api_ef_objects:
        climatiq_api_ef_object.activity_id = climatiq_api_ef_object.raw_data['activity_id']

        # Get the PantasEmissionFactor object corresponding to the climatiq_api_ef_object
        pantas_ef_object = PantasEmissionFactorModel.objects.get(
            external_source_emission_factor=climatiq_api_ef_object)
        pantas_ef_object.activity_id = climatiq_api_ef_object.raw_data['activity_id']
        pantas_ef_objects.append(pantas_ef_object)

    # Bulk update the activity_id in the models
    ExternalSourceEmissionFactorModel.objects.bulk_update(
        climatiq_api_ef_objects, ['activity_id'], batch_size=10000)
    PantasEmissionFactorModel.objects.bulk_update(
        pantas_ef_objects, ['activity_id'], batch_size=10000)


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0007_historicalpantasemissionfactor_name_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsourceemissionfactor',
            name='activity_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalexternalsourceemissionfactor',
            name='activity_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalpantasemissionfactor',
            name='activity_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalupdateexternalsourceemissionfactor',
            name='activity_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='pantasemissionfactor',
            name='activity_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='updateexternalsourceemissionfactor',
            name='activity_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.RunPython(update_emission_factor_activity_id,
                             migrations.RunPython.noop),
    ]
